name: notebook
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  path: ^1.9.0
  path_provider: ^2.1.4
  intl: ^0.19.0
  idb_shim: ^2.6.1+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1  # Include this package

flutter:
  uses-material-design: true
  assets:
    - assets/icons/notebook.png  # Path to your notebook icon

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/notebook.png"  # Path to your notebook icon
